import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../api";
import EmptyResults from "../components/EmptyResults";
import FilterBar, { FilterChips, SearchField, ViewToggle } from "../components/FilterBar";
import PageHeader from "../components/PageHeader";

function formatSize(bytes) { if (!bytes) return "—"; if (bytes < 1024) return `${bytes} B`; if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1048576).toFixed(1)} MB`; }

export default function FilesPage({ notify }) {
  const [summary, setSummary] = useState(null); const [listing, setListing] = useState(null); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(false); const [query, setQuery] = useState(""); const [type, setType] = useState("all"); const [view, setView] = useState("split");
  const loadDirectory = useCallback(async (path = "") => { setLoading(true); try { setListing(await api(`/api/workspace/files?path=${encodeURIComponent(path)}`)); setSelected(null); setQuery(""); } catch (error) { notify(error.message, true); } finally { setLoading(false); } }, [notify]);
  useEffect(() => { Promise.all([api("/api/workspace"), api("/api/workspace/files")]).then(([nextSummary, nextListing]) => { setSummary(nextSummary); setListing(nextListing); }).catch((error) => notify(error.message, true)); }, [notify]);
  const filtered = useMemo(() => (listing?.entries || []).filter((entry) => (!query || entry.name.toLowerCase().includes(query.toLowerCase())) && (type === "all" || type === entry.kind || (type === "previewable" && entry.previewable))), [listing, query, type]);
  async function open(entry) { if (entry.kind === "directory") return loadDirectory(entry.path); if (!entry.previewable) return notify("This file type is not available for safe preview.", true); try { setSelected(await api(`/api/workspace/file?path=${encodeURIComponent(entry.path)}`)); if (view === "list") setView("split"); } catch (error) { notify(error.message, true); } }
  const crumbs = listing?.path ? listing.path.split("/") : []; const clear = () => { setQuery(""); setType("all"); };
  return <><PageHeader eyebrow="READ-ONLY CONTEXT" title="Workspace files" description="Browse by folder, filter the current view, and preview only the file you select." actions={summary && <span className="read-only-badge">READ ONLY</span>} /><div className="workspace-compact"><span><strong>{summary?.root_name}</strong><small>{summary?.root_path}</small></span><span>{summary?.files} files</span><span>{summary?.directories} folders</span></div><FilterBar resultCount={filtered.length} hasFilters={Boolean(query || type !== "all")} onClear={clear}><SearchField value={query} onChange={setQuery} placeholder="Filter this folder" /><FilterChips value={type} onChange={setType} options={["all", "directory", "file", "previewable"]} /><ViewToggle value={view} onChange={setView} options={[["split", "◫", "Split preview"], ["list", "☷", "List only"]]} /></FilterBar><div className={`file-browser ${view === "list" ? "list-only" : ""}`}><section className="file-pane"><div className="breadcrumbs"><button onClick={() => loadDirectory("")}>{listing?.root_name || "Workspace"}</button>{crumbs.map((crumb, index) => <button key={`${crumb}-${index}`} onClick={() => loadDirectory(crumbs.slice(0, index + 1).join("/"))}>/ {crumb}</button>)}</div>{listing?.parent !== null && <button className="file-row parent" onClick={() => loadDirectory(listing.parent)}>↰ <span>Parent directory</span></button>}{loading ? <div className="empty-state">Loading directory…</div> : filtered.length ? filtered.map((entry) => <button className={`file-row ${selected?.path === entry.path ? "selected" : ""}`} key={entry.path} onClick={() => open(entry)}><span className="file-icon">{entry.kind === "directory" ? "▰" : "▱"}</span><span><strong>{entry.name}</strong><small>{entry.kind === "directory" ? "Folder" : formatSize(entry.size)}</small></span><b>{entry.kind === "directory" ? "›" : entry.previewable ? "Preview" : "Restricted"}</b></button>) : <EmptyResults onClear={clear} />}</section>{view === "split" && <section className="preview-pane">{selected ? <><div className="preview-head"><div><span>{selected.language.toUpperCase()}</span><h2>{selected.name}</h2><p>{selected.path} · {formatSize(selected.size)}{selected.truncated ? " · preview truncated" : ""}</p></div></div><pre><code>{selected.content}</code></pre></> : <div className="preview-empty"><span>▱</span><h2>Select a file</h2><p>Details stay hidden until you choose an allowed source or text file.</p></div>}</section>}</div></>;
}

